name: Sync Image
description: 同步一个镜像
labels:
- sync image
body:
- type: markdown
  attributes:
    value: |
      # ↑↑↑↑↑↑↑↑↑↑↑ 填入你要同步的 Image
      ## 请包含 域名/路径:标签

- type: checkboxes
  attributes:
    label: domain
    options:
    - label: 请确保包含域名(domain)
- type: markdown
  attributes:
    value: |
      - 如 docker.io/
      - 如 registry.k8s.io/
      - 如果不包含域名, 需要主动添加默认的 docker.io/

- type: checkboxes
  attributes:
    label: tag
    options:
    - label: 请确保包含镜像的标签(tag)
- type: markdown
  attributes:
    value: |
      - 如 :latest
      - 如 :v1

- type: checkboxes
  attributes:
    label: check
    options:
    - label: 请确保这个镜像真实存在
- type: markdown
  attributes:
    value: |
      - 如 docker.io/library/busybox:latest
      - 如 docker.io/kindest/node:v1.30.0
      - 如 registry.k8s.io/kubectl:v1.30.0

- type: markdown
  attributes:
    value: |
      有疑问反馈, 请添加我们的企微群 [#4183](https://github.com/DaoCloud/public-image-mirror/issues/4183)
