name: Sync Image
description: 同步一个镜像 (需要 Image 已在白名单里)
labels:
- sync image
body:
- type: markdown
  attributes:
    value: |
      # ↑↑↑↑↑↑↑↑↑↑↑ 填入你要同步的 Image
      ## 请包含 域名/路径:标签

- type: dropdown
  attributes:
    label: 镜像架构
    description: 请选择要同步的目标架构
    options:
    - linux/amd64
    - linux/386
    - linux/arm64
    - linux/arm/v6
    - linux/arm/v7
    - linux/ppc64le
    - linux/s390x
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      请确保包含域名(domain)
      - 如 docker.io/
      - 如 registry.k8s.io/
      - 如果不包含域名, 需要主动添加默认的 docker.io/

- type: markdown
  attributes:
    value: |
      请确保包含镜像的标签(tag)
      - 如 :latest
      - 如 :v1

- type: markdown
  attributes:
    value: |
      请确保这个镜像真实存在
      - 如 docker.io/library/busybox:latest
      - 如 docker.io/kindest/node:v1.30.0
      - 如 registry.k8s.io/kubectl:v1.30.0

- type: markdown
  attributes:
    value: |
      有疑问反馈, 请添加我们的企微群 [#4183](https://github.com/DaoCloud/public-image-mirror/issues/4183)
