name: Manual Deep Sync
run-name: Manual Deep Sync ${{ inputs.image }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Manually synchronize a image'
        required: true
        type: string

jobs:
  sync-images:
    runs-on: ubuntu-latest
    if: github.repository == 'DaoCloud/public-image-mirror'
    steps:
      - name: Set up crproxy
        run: |
          wget https://github.com/DaoCloud/crproxy/releases/download/v0.13.0-alpha.154/crproxy_linux_amd64 -O /usr/local/bin/crproxy && chmod +x /usr/local/bin/crproxy
  
      - name: Sync Images to OSS&OBS
        run: |
          ORIGIN_IMAGE=${{ github.event.inputs.image }}
          /usr/local/bin/crproxy sync --deep --max-warn 1 ${{ secrets.STORAGE_ARGS }} --user '${{ secrets.OCI_USER }}' --list ${ORIGIN_IMAGE}
  